# Data Preparation

This notebook focuses on preparing the Hyperliquid trader dataset and the Bitcoin Fear & Greed sentiment dataset for analysis. The preprocessing steps include data inspection, handling missing values and duplicates, converting data types, standardizing date formats, and merging both datasets into a single analysis-ready dataset.

## Objectives

The objectives of this notebook are to:

- Load the trader and market sentiment datasets.
- Inspect the structure and quality of each dataset.
- Check for missing values and duplicate records.
- Convert timestamp columns to appropriate datetime formats.
- Align both datasets using a common daily date.
- Merge trader data with the corresponding daily market sentiment.
- Validate the merged dataset before exploratory data analysis.

### Dataset Inspection

The first step is to understand the structure of both datasets by examining:

- Number of rows and columns
- Column names
- Data types
- Summary of missing values
- Presence of duplicate records

This helps identify any cleaning or preprocessing required before analysis.

In [1]:
import pandas as pd
print("Pandas loaded")

Pandas loaded

In [2]:
sentiment_df = pd.read_csv("../data/raw/fear_greed_index.csv")
trader_df = pd.read_csv("../data/raw/historical_data.csv")

In [3]:
print("Sentiment Dataset Shape:", sentiment_df.shape)
print("Trader Dataset Shape:", trader_df.shape)

Sentiment Dataset Shape: (2644, 4)
Trader Dataset Shape: (211224, 16)

In [4]:
sentiment_df.head()

    timestamp  value classification        date
0  1517463000     30           Fear  01-02-2018
1  1517549400     15   Extreme Fear  02-02-2018
2  1517635800     40           Fear  03-02-2018
3  1517722200     24   Extreme Fear  04-02-2018
4  1517808600     11   Extreme Fear  05-02-2018

In [5]:
sentiment_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2644 entries, 0 to 2643
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   timestamp       2644 non-null   int64
 1   value           2644 non-null   int64
 2   classification  2644 non-null   str
 3   date            2644 non-null   str
dtypes: int64(2), str(2)
memory usage: 82.8 KB

In [6]:
trader_df.head()

,Account,Coin,Execution Price,Size Tokens,Size USD,Side,Timestamp IST,Start Position,Direction,Closed PnL,Transaction Hash,Order ID,Crossed,Fee,Trade ID,Timestamp
0,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9769,986.87,7872.16,BUY,02-12-2024 22:50,0.000000,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.345404,8.950000e+14,1.730000e+12
1,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9800,16.00,127.68,BUY,02-12-2024 22:50,986.524596,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.005600,4.430000e+14,1.730000e+12
2,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9855,144.09,1150.63,BUY,02-12-2024 22:50,1002.518996,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050431,6.600000e+14,1.730000e+12
3,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9874,142.98,1142.04,BUY,02-12-2024 22:50,1146.558564,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050043,1.080000e+15,1.730000e+12
4,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9894,8.73,69.75,BUY,02-12-2024 22:50,1289.488521,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.003055,1.050000e+15,1.730000e+12

In [7]:
trader_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 211224 entries, 0 to 211223
Data columns (total 16 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Account           211224 non-null  str
 1   Coin              211224 non-null  str
 2   Execution Price   211224 non-null  float64
 3   Size Tokens       211224 non-null  float64
 4   Size USD          211224 non-null  float64
 5   Side              211224 non-null  str
 6   Timestamp IST     211224 non-null  str
 7   Start Position    211224 non-null  float64
 8   Direction         211224 non-null  str
 9   Closed PnL        211224 non-null  float64
 10  Transaction Hash  211224 non-null  str
 11  Order ID          211224 non-null  int64
 12  Crossed           211224 non-null  bool
 13  Fee               211224 non-null  float64
 14  Trade ID          211224 non-null  float64
 15  Timestamp         211224 non-null  float64
dtypes: bool(1), float64(8), int64(1), str(6)
memory usage: 24.4 MB

In [8]:
sentiment_df.isnull().sum()

timestamp         0
value             0
classification    0
date              0
dtype: int64

In [9]:
trader_df.isnull().sum()

Account             0
Coin                0
Execution Price     0
Size Tokens         0
Size USD            0
Side                0
Timestamp IST       0
Start Position      0
Direction           0
Closed PnL          0
Transaction Hash    0
Order ID            0
Crossed             0
Fee                 0
Trade ID            0
Timestamp           0
dtype: int64

In [10]:
sentiment_df.duplicated().sum()

np.int64(0)

In [11]:
trader_df.duplicated().sum()

np.int64(0)

### Data Type Conversion

Several columns required conversion to appropriate data types before analysis.

- The `Timestamp IST` column was converted from string to datetime.
- The sentiment dataset's `date` column was converted to datetime.
- Numeric columns such as execution price, trade size, fee, and profit/loss were verified to have appropriate numeric data types.

Using correct data types enables accurate calculations, filtering, and time-series analysis.

In [12]:
trader_df.dtypes

Account                 str
Coin                    str
Execution Price     float64
Size Tokens         float64
Size USD            float64
Side                    str
Timestamp IST           str
Start Position      float64
Direction               str
Closed PnL          float64
Transaction Hash        str
Order ID              int64
Crossed                bool
Fee                 float64
Trade ID            float64
Timestamp           float64
dtype: object

In [13]:
trader_df["Timestamp IST"] = pd.to_datetime(
    trader_df["Timestamp IST"],
    format="%d-%m-%Y %H:%M"
)

In [14]:
trader_df["Timestamp IST"].dtype

dtype('<M8[us]')

### Date Standardization

The trader dataset records transactions at the timestamp level, whereas the market sentiment dataset provides one sentiment value per day.

To align both datasets, only the date component was extracted from the trader timestamps. This created a common daily date field that could be used to merge both datasets.

In [15]:
trader_df["date"] = trader_df["Timestamp IST"].dt.date

In [16]:
sentiment_df["date"] = pd.to_datetime(
    sentiment_df["date"],
    format="%d-%m-%Y"
)

In [17]:
sentiment_df["date"] = sentiment_df["date"].dt.date

### Merging the Datasets

The trader dataset was merged with the market sentiment dataset using the common daily date.

A left join was performed to preserve all trading records while attaching the corresponding daily market sentiment (Fear or Greed) to each trade.

This merged dataset forms the foundation for subsequent exploratory data analysis and trader performance evaluation.

In [18]:
merged_df = pd.merge(
    trader_df,
    sentiment_df,
    on="date",
    how="left"
)

### Merge Validation

After merging, the resulting dataset was validated by:

- Verifying the number of records
- Checking for unmatched sentiment values
- Inspecting data types
- Confirming successful alignment of daily market sentiment with each trading record

The final dataset is now ready for feature engineering and exploratory data analysis.

In [19]:
merged_df.head()

,Account,Coin,Execution Price,Size Tokens,Size USD,Side,Timestamp IST,Start Position,Direction,Closed PnL,Transaction Hash,Order ID,Crossed,Fee,Trade ID,Timestamp,date,timestamp,value,classification
0,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9769,986.87,7872.16,BUY,2024-12-02 22:50:00,0.000000,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.345404,8.950000e+14,1.730000e+12,2024-12-02,1.733117e+09,80.0,Extreme Greed
1,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9800,16.00,127.68,BUY,2024-12-02 22:50:00,986.524596,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.005600,4.430000e+14,1.730000e+12,2024-12-02,1.733117e+09,80.0,Extreme Greed
2,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9855,144.09,1150.63,BUY,2024-12-02 22:50:00,1002.518996,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050431,6.600000e+14,1.730000e+12,2024-12-02,1.733117e+09,80.0,Extreme Greed
3,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9874,142.98,1142.04,BUY,2024-12-02 22:50:00,1146.558564,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050043,1.080000e+15,1.730000e+12,2024-12-02,1.733117e+09,80.0,Extreme Greed
4,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9894,8.73,69.75,BUY,2024-12-02 22:50:00,1289.488521,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.003055,1.050000e+15,1.730000e+12,2024-12-02,1.733117e+09,80.0,Extreme Greed

In [20]:
merged_df["classification"].isnull().sum()

np.int64(6)

In [21]:
merged_df.shape

(211224, 20)

In [22]:
merged_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 211224 entries, 0 to 211223
Data columns (total 20 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Account           211224 non-null  str
 1   Coin              211224 non-null  str
 2   Execution Price   211224 non-null  float64
 3   Size Tokens       211224 non-null  float64
 4   Size USD          211224 non-null  float64
 5   Side              211224 non-null  str
 6   Timestamp IST     211224 non-null  datetime64[us]
 7   Start Position    211224 non-null  float64
 8   Direction         211224 non-null  str
 9   Closed PnL        211224 non-null  float64
 10  Transaction Hash  211224 non-null  str
 11  Order ID          211224 non-null  int64
 12  Crossed           211224 non-null  bool
 13  Fee               211224 non-null  float64
 14  Trade ID          211224 non-null  float64
 15  Timestamp         211224 non-null  float64
 16  date              211224 non-null  object
 17  timestamp         211218 non-null  float64
 18  value             211218 non-null  float64
 19  classification    211218 non-null  str
dtypes: bool(1), datetime64[us](1), float64(10), int64(1), object(1), str(6)
memory usage: 30.8+ MB

In [23]:
merged_df.head()

,Account,Coin,Execution Price,Size Tokens,Size USD,Side,Timestamp IST,Start Position,Direction,Closed PnL,Transaction Hash,Order ID,Crossed,Fee,Trade ID,Timestamp,date,timestamp,value,classification
0,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9769,986.87,7872.16,BUY,2024-12-02 22:50:00,0.000000,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.345404,8.950000e+14,1.730000e+12,2024-12-02,1.733117e+09,80.0,Extreme Greed
1,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9800,16.00,127.68,BUY,2024-12-02 22:50:00,986.524596,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.005600,4.430000e+14,1.730000e+12,2024-12-02,1.733117e+09,80.0,Extreme Greed
2,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9855,144.09,1150.63,BUY,2024-12-02 22:50:00,1002.518996,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050431,6.600000e+14,1.730000e+12,2024-12-02,1.733117e+09,80.0,Extreme Greed
3,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9874,142.98,1142.04,BUY,2024-12-02 22:50:00,1146.558564,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050043,1.080000e+15,1.730000e+12,2024-12-02,1.733117e+09,80.0,Extreme Greed
4,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9894,8.73,69.75,BUY,2024-12-02 22:50:00,1289.488521,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.003055,1.050000e+15,1.730000e+12,2024-12-02,1.733117e+09,80.0,Extreme Greed

After merging the trader and sentiment datasets on the date field, six records (0.003% of the data) had no corresponding market sentiment information. Since the objective of the analysis was to compare trading behavior under Fear and Greed conditions, these unmatched records were removed from the dataset.

In [24]:
merged_df = merged_df[merged_df["classification"].notna()]

In [25]:
merged_df.info()

<class 'pandas.DataFrame'>
Index: 211218 entries, 0 to 211223
Data columns (total 20 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Account           211218 non-null  str
 1   Coin              211218 non-null  str
 2   Execution Price   211218 non-null  float64
 3   Size Tokens       211218 non-null  float64
 4   Size USD          211218 non-null  float64
 5   Side              211218 non-null  str
 6   Timestamp IST     211218 non-null  datetime64[us]
 7   Start Position    211218 non-null  float64
 8   Direction         211218 non-null  str
 9   Closed PnL        211218 non-null  float64
 10  Transaction Hash  211218 non-null  str
 11  Order ID          211218 non-null  int64
 12  Crossed           211218 non-null  bool
 13  Fee               211218 non-null  float64
 14  Trade ID          211218 non-null  float64
 15  Timestamp         211218 non-null  float64
 16  date              211218 non-null  object
 17  timestamp         211218 non-null  float64
 18  value             211218 non-null  float64
 19  classification    211218 non-null  str
dtypes: bool(1), datetime64[us](1), float64(10), int64(1), object(1), str(6)
memory usage: 32.4+ MB

In [26]:
merged_df.to_csv("../data/processed/trader_sentiment_processed.csv", index=False)

## Summary

The data preparation process ensured that both datasets were cleaned, standardized, and successfully integrated into a single analysis-ready dataset.

The prepared dataset enables further investigation into how market sentiment influences trader behavior, profitability, trading activity, and risk-taking patterns on the Hyperliquid platform.